# Generated by Django 3.2.7 on 2021-11-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='domain',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.web_information'),
        ),
    ]
