# Generated by Django 3.2.7 on 2021-11-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='domain',
            field=models.CharField(default='sendo', max_length=40),
        ),
    ]
