# Generated by Django 3.2.7 on 2021-11-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categort',
            field=models.TextField(default='', max_length=100),
        ),
    ]
