# Generated by Django 3.2.7 on 2021-11-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_categort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categort',
            new_name='category',
        ),
    ]
