# Generated by Django 3.2.7 on 2021-11-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211130_2132'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER product_update_trigger
            BEFORE INSERT OR UPDATE OF name, vector_column
            ON main_product
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(vector_column,'pg_catalog.english',name);

            UPDATE main_product SET vector_column = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS product_update_trigger
            ON main_product;
            '''),
    ]
