# Generated by Django 3.2.7 on 2021-11-30 16:21

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_create_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
