# Generated by Django 3.2.7 on 2021-12-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mycat',
            field=models.IntegerField(default=0),
        ),
    ]
