# Generated by Django 3.2.7 on 2021-12-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_mycat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(max_length=2000),
        ),
    ]
