# Generated by Django 3.2.7 on 2021-12-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='domain',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='mycat',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
