# Generated by Django 3.2.7 on 2021-12-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211205_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_category',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='my_category',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
