# Generated by Django 3.2.7 on 2021-09-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weburl', models.TextField(default='', max_length=100)),
                ('searchurl', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='navigation_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_code', models.CharField(default='', max_length=25)),
                ('url_code', models.CharField(default='', max_length=25)),
                ('price_code', models.CharField(default='', max_length=25)),
                ('product_code_code', models.CharField(default='', max_length=25)),
                ('weburl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.website')),
            ],
        ),
    ]
