# Generated by Django 3.2.7 on 2021-09-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation_code',
            name='seperator_attr',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='navigation_code',
            name='seperator_attr_value',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='navigation_code',
            name='seperator_tag',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='navigation_code',
            name='name_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='navigation_code',
            name='price_code',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='navigation_code',
            name='url_code',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='website',
            name='searchurl',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='website',
            name='weburl',
            field=models.TextField(default='', max_length=50),
        ),
    ]
