# Generated by Django 3.2.7 on 2021-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210917_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation_code',
            name='name_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='navigation_code',
            name='price_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='navigation_code',
            name='product_code_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='navigation_code',
            name='url_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
